set(_CATKIN_CURRENT_PACKAGE "object_detector")
set(object_detector_VERSION "0.0.0")
set(object_detector_MAINTAINER "rohan <rohan@todo.todo>")
set(object_detector_PACKAGE_FORMAT "1")
set(object_detector_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "message_generation" "cv_bridge" "image_transport" "tf" "eigen_conversions")
set(object_detector_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime" "cv_bridge" "image_transport" "tf" "eigen_conversions")
set(object_detector_BUILDTOOL_DEPENDS "catkin")
set(object_detector_BUILDTOOL_EXPORT_DEPENDS )
set(object_detector_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime" "cv_bridge" "image_transport" "tf" "eigen_conversions")
set(object_detector_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime" "cv_bridge" "image_transport" "tf" "eigen_conversions")
set(object_detector_TEST_DEPENDS )
set(object_detector_DOC_DEPENDS )
set(object_detector_URL_WEBSITE "")
set(object_detector_URL_BUGTRACKER "")
set(object_detector_URL_REPOSITORY "")
set(object_detector_DEPRECATED "")